# Site settings
title: Thomas Barras
description: "My blog about Computer Science."
url: "http://exced.github.io"
twitter_username: exced_
github_username:  exced
facebook_username: barras.thomas
linkedin_username: thomas-barras-b487a8a1/
email_username:  thomas.barras26@gmail.com
author:
  name: "Thomas Barras"
  email: "thomas.barras26@gmail.com"
  url: "http://exced.github.io"

# Build settings
baseurl: # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
highlighter: rouge
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
